version: "3"
services:
  # 서비스 입장하는 입구 역할. 하나의 포트로 모든 서비스 연결할 수 있도록 만들어주기 위해 build
  ReverseProxyServer:
    image: nginx:stable
    ports:
      - "8756:8080"
    volumes:
      - /etc/localtime:/etc/localtime
      - ./source/nginx/nginx.conf:/etc/nginx/nginx.conf

  # dji에서 pilot2 개발을 위해 제공하는 샘플 프론트 페이지 활용
  pilot2sample:
    build: ./sample
    image: sinto-pilot2-sample
    volumes:
      - ./sample/app.js:/app/app.js

  # 개발중인 백엔드(main). 회사에선 nodejs로 개발. 현 포폴에선 python으로 개발.
  pilot2back:
    build: ./CloudAPI
    image: sinto-pilot2-back
    depends_on:
      - emqx-broker
    volumes:
      - ./CloudAPI/source:/home/pilot/source
    restart: "always"
    networks:
      - full_default

  # broker - client || subscribe - publish 개념으로 서버간 메세지 주고받는 프로토콜
  emqx-broker:
    image: emqx:4.4
    ports:
      - "18083:18083"
    environment:
      - EMQX_ALLOW_ANONYMOUS=true

  # livestreaming service 위해 테스트 중인 rtmp - webrtc 변환 서버
  ome:
    image: airensoft/ovenmediaengine:latest
    # 1935: rtmp / 3333: webrtc / 3478: for getting out webrtc
    ports:
      - 1935:1935
      # - 9999:9999/udp
      # - 9000:9000
      - 3333:3333
      - 3478:3478                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
      # - 10000-10009:10000-10009/udp
    environment:
      - OME_HOST_IP="Your IP ADDRESS"

  # livestreaming player
  ovenplayer:
    image: airensoft/ovenplayerdemo:latest
    ports:
      - 8090:80

  # cloud storage(OSS)
  minio:
    image: minio/minio
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER : team3
      MINIO_ROOT_PASSWORD: visumy00
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data