# 일단 Ingress Server에서 해당 서비스로 연결되는지 확인해봐야함
# 만약 안된다면? -> NodePort 지정으로 서버에 접근하면 바로 연결되도록 해주자. (단, 이렇게 하면 보안상 문제가 생길 수 있겠다...)
apiVersion: v1
kind: Service
metadata:
  name: service-pilot2-ome
spec:
  selector:
    app: pilot2-ome
  ports:
    - name: rtmp
      protocol: TCP
      port: 1935
      targetPort: 1935
    - name: webrtc
      protocol: TCP
      port: 3333
      targetPort: 3333
    - name: stun
      protocol: TCP
      port: 3478
      targetPort: 3478
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-pilot2-ome
  annotations:
    kubernetes-deploy-test: first
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pilot2-ome
  progressDeadlineSeconds: 600 #600초동안 업데이트 진행하지 못하면 실패처리 후 되돌리겠다.
  revisionHistoryLimit: 10 #롤링업데이트 후 남아있는 버젼을 10개까지만 남겨둔다.
  strategy:
    rollingUpdate:
      maxSurge: 25
      maxUnavailable: 25
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pilot2-ome
    spec:
      containers:
      - name: container-pilot2-ome
        image: localhost:1234/pilot2-ome
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 1935
        - containerPort: 3333
        - containerPort: 3478
