apiVersion: v1
kind: Service
metadata:
  name: service-pilot2-database
spec:
  selector:
    app: pilot2-database
  ports:
    - name: websocket
      protocol: TCP
      port: 8083
      targetPort: 8083
    - name: dashboard
      protocol: TCP
      port: 18083
      targetPort: 18083
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sf-pilot2-emqx
spec:
  replicas: 3
  serviceName: emqx
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: pilot2-emqx
  template:
    metadata:
      labels:
        app: pilot2-emqx
    spec:
      containers:
      - name: container-pilot2-emqx
        image: localhost:1234/pilot2-emqx
        ports:
        - containerPort: 8083 #ws 위에서 동작하는! 뒤에 /mqtt가 붙어야함
        - containerPort: 18083 #대시보드