server:
  port: 6789
spring:
  application:
    name: cloud-api-sample
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://cloud_api_sample_mysql:3306/cloud_sample?useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
      initial-size: 10
      min-idle: 10
      max-active: 20
      max-wait: 60000

  redis:
    host: cloud_api_sample_redis
    port: 6379
    database: 0
    username: # if you enable
    password:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB

jwt:
  issuer: DJI
  subject: CloudApiSample
  secret: CloudApiSample
  age: 86400

mqtt:
  # @see com.dji.sample.component.mqtt.model.MqttUseEnum
  # BASIC parameters are required.
  BASIC:
    protocol: MQTT # @see com.dji.sample.component.mqtt.model.MqttProtocolEnum
    # host: 192.168.0.70
    host: 211.189.132.21
    port: 1883
    username: JavaServer
    password: 123456
    client-id: 123456
    # If the protocol is ws/wss, this value is required.
    path:
    # Topics that need to be subscribed when initially connecting to mqtt, multiple topics are divided by ",".
    inbound-topic: sys/product/+/status,thing/product/+/requests

url:
  manage:
    prefix: /manage
    version: /api/v1
  map:
    prefix: /map
    version: /api/v1
  media:
    prefix: /media
    version: /api/v1
  wayline:
    prefix: /wayline
    version: /api/v1
  storage:
    prefix: /storage
    version: /api/v1
  control:
    prefix: /control
    version: /api/v1

# Tutorial: https://www.alibabacloud.com/help/en/object-storage-service/latest/use-a-temporary-credential-provided-by-sts-to-access-oss
# oss:
#   enable: False
#   provider: ali # @see com.dji.sample.component.OssConfiguration.model.enums.OssTypeEnum
#   endpoint: https://oss-cn-hangzhou.aliyuncs.com
#   access-key: Please enter your access key.
#   secret-key: Please enter your secret key.
#   expire: 3600
#   region: Please enter your oss region. # cn-hangzhou
#   role-session-name: cloudApi
#   role-arn: Please enter your role arn. # acs:ram::123456789:role/stsrole
#   bucket: Please enter your bucket name.
#   object-dir-prefix: Please enter a folder name.

#oss:
#  enable: true
#  provider: aws
#  endpoint: https://s3.us-east-1.amazonaws.com
#  access-key:
#  secret-key:
#  expire: 3600
#  region: us-east-1
#  role-session-name: cloudApi
#  role-arn:
#  bucket: cloudapi-bucket
#  object-dir-prefix: wayline

# oss:
#  enable: true
#  provider: minio
#  endpoint: http://211.189.132.21:9000
#  access-key: Sbq1tPycFIeWuVYw
#  secret-key: TbdVQJxgIbveASbzi2PUfym8WLVMlPRa
#  bucket: neighbor-cloudapi
#  expire: 3600
#  region: ap-northeast-2
#  object-dir-prefix: wayline

oss:
 enable: true
 provider: minio
 endpoint: http://211.189.132.21:9000
 access-key: qdKDwKl8k3RkEsnY
 secret-key: jhhHHAchEcQKqJgfa3j9BmnxUZzqp7FN
 bucket: neighbor-cloudapi
 expire: 3600
 region: ap-northeast-2
 object-dir-prefix: wayline


logging:
  level:
    com.dji.sample: debug
  file:
    name: logs/cloud-api-sample.log

ntp:
  server:
    host: Google.mzr.me

# To create a license for an application: https://developer.dji.com/user/apps/#all
cloud-api:
  app:
    id: 131583
    key: 6b91e021824438126c5c8534f449e16
    license: bRVQNN3IkxSXuy5D62KMyV1PKXlTQWadDnGFnPnOiaKkEFoWm9dgDGLR9VT1snckVYH2p9Y/DuN4+bou8vLMThPgrOCVJWFFrcqUPxLL3h3xZtXxvIl0nMFh/fGToZAGpvu98D9Oip5ProT5QXn2u4V8INgGiCT6xFt8ZktGUNI=